[package]
name = "hcp-rs"
version = "0.1.0"
edition = "2021"

[features]
default = ["gsl_compat"]
gsl_compat = ["dep:GSL"]

[dependencies]
graph-io-gml = "0.3"
petgraph = "0.5"
GSL = { version = "7.0", optional = true }
mt19937 = "2.0.1"
rand = "0.8.5"
